name: Waka Readme

on:
  schedule:
    - cron: '30 20 * * *' # 4:30AM +8:00
    - corn: '30 12 * * *' # 20:30PM +8:00
  workflow_dispatch:
  
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master # for Gitlab(Chinses simplefied)
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_OS: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_TIMEZONE: "False"
          LOCALE: "zh"
          
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pull latest from GitHub # keep the source updated
        run: git pull origin main
        
      - uses: saderi/push-to-gitlab@v1
        with:
            gitlab_repository: ${{ secrets.GITLAB_REPO }} # do not include https://
            gitlab_token: ${{ secrets.GITLAB_TOKEN }}
      
      - uses: anmol098/waka-readme-stats@master # for Github
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_OS: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_TIMEZONE: "False"
          
