name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
  
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_OS: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_TIMEZONE: "False"
          
      - name: Checkout
        uses: actions/checkout@v2
        
      - uses: saderi/push-to-gitlab@v1
        with:
            gitlab_repository: ${{ secrets.GITLAB_REPO }} # do not include https://
            gitlab_token: ${{ secrets.GITLAB_TOKEN }}
          
          
